#!/bin/sh -e

export RUSTFLAGS='-D warnings'

cargo fmt --all --check
cargo clippy --all-targets --no-default-features --features client,server,sound
cargo test --all-targets --no-default-features --features client,server,sound
